export enum TechnoTypes {
  JavaScript = 'JavaScript',
  HTML = 'HTML',
  CSS = 'CSS',
  React = 'React',
  NextJS = 'NextJS',
  TypeScript = 'TypeScript',
  NodeJS = 'NodeJS',
  Sass = 'Sass',
  MongoDB = 'MongoDB',
  Redux = 'Redux',
  Figma = 'Figma',
  MaterialUI = 'MaterialUI',
  Mantine = 'Mantine',
  Vue = 'Vue',
}
